apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: nodejsapp
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: nodejsapp
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
