version: "3.8"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production

volumes:
  node_data: 